// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MovieIndexController from "./movie_index_controller"
application.register("movie-index", MovieIndexController)

import TestController from "./test_controller"
application.register("test", TestController)
